### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Angular#18]
Due to the RGPD, we need to add a cookie consent.
Boosted [cookie consent](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/tree/cookie-consent) can be an example.

**Comment by liyokuna** [comment]
No cookies are created.
npm package that can help for further use.
https://www.npmjs.com/package/cookieconsent

**Comment by liyokuna** [comment]
using this cookie consent package
https://tinesoft.github.io/ngx-cookieconsent/getting-started

**Comment by liyokuna** [comment]
Hello @Aniort ,

I need you to test the accessiblity of the pop over cookie.
here is the [link](https://deploy-preview-41--ng-boosted.netlify.com/).

**Comment by Aniort** [comment]
not validated :
- you must remove aria-label="cookieconsent" from the div (aria-labelledby is enough)
- you do you use links with ria roles of button instead of real buttons
- you don't need aria-label in these links because text links are understandables, but if you want to use aria-label translate them 
- you must put the text of the popup and the links inside a <p> tag
- translate the "learn more" link

**Comment by liyokuna** [comment]
Hello @Aniort,
can you check all the changes [right here](https://deploy-preview-41--ng-boosted.netlify.com/).

**Comment by liyokuna** [comment]
Hello @StreiffBerenice , Check the accessibility of the pop up, please.
here is the [link](https://deploy-preview-41--ng-boosted.netlify.com/)

**Comment by StreiffBerenice** [comment]
This is what I see when I activate yout link I don't understand what do you expect. 
![image](https://user-images.githubusercontent.com/42869219/57087790-21255380-6d01-11e9-8a9f-93fb96aedf36.png)
