### ISSUE TITLE
Compatibility Node 14

### ISSUE THREAD

**Issue by L-Luciano** [Orange-OpenSource/Orange-Boosted-Angular#223]
Hello,

I use ng-boosted 5.1.4 with angular 8.
Is it compatible with node 14 ?

I have errors on package deasync (V0.1.16) wich come from sass-math-pow dependencies.
Deasync looks like compatible with node 13.

Do you have a workaround ?

Regards,
Laurent

**Comment by Lausselloic** [comment]
Hello,

sass-math-pow is needed only if you recompile boosted.scss files to generate your output.

So if you really need to do it I think the only way is to go up in ng-boosted to also go up in boosted version where sass-math-pow have been remove.

Otherwise use the boosted.css files and remove the dependency sass-math-pow

**Comment by Lausselloic** [comment]
just check and sass-math-pow have been removed from boosted dependecy in v4.5.0

**Comment by Lausselloic** [comment]
ng-boosted 5.2.3 used boosted 4.5.0 and angular 8 if you could try to upgrade?

**Comment by Lausselloic** [comment]
@L-Luciano please reopen if you're still locked.
