### ISSUE TITLE
Boosted with ngx-toastr

### ISSUE THREAD

**Issue by youssefabc** [Orange-OpenSource/Orange-Boosted-Angular#26]
Hello,

I have a problem when change version from boosted 4.1.3 to 4.2.2.
I am using this library https://www.npmjs.com/search?q=ngx-toastr it's work fine with boosted 4.1.3 but not work with 4.2.2 version.

Thanks for your help and support

**Comment by liyokuna** [comment]
Hello @youssefabc 

I look to your issue and it is not relate to ng-boosted and neither boosted.
Try this config and let me know :
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "paths": {
      "@angular/*": [
      "node_modules/@angular/*"
      ]
      }       
  }
}
and concerning ng-boosted package, please just set the version of ng-boosted equal to ng-botstrap in order to avoid incompatibilities bugs.

**Comment by liyokuna** [comment]
This is related to bootstrap[ v 4.2.1](https://stackblitz.com/edit/angular-fb8sf8?embed=1&file=package.json). There is a bug on css class that messing up ngx toatr.
Use the next package.
