### ISSUE TITLE
O-Calendar updates

### ISSUE THREAD

**Issue by liyokuna** [Orange-OpenSource/Orange-Boosted-Angular#31]
Fisrt changes to do: 
- Use [class.stylename] = condition instead of traditional class, example in switch o-calendar. https://github.com/Orange-OpenSource/Orange-Boosted-Angular/commit/b7525463fc5316867830f02ee27d3dd3b0124745
- change call functions inside  o-calendar
- Internationalization of O-calendar. test

**Comment by StreiffBerenice** [comment]
@liyokuna 

- **POSITIVE POINT**: the calendar table is accessible
And it's not so easy to obtain ! :) 
But: 
----- 
- Why don't you pu the calendar button after the textual field? To me, it would be more logical to have firstly the possibility to use the textual field and to have after, in the tabulation order, to use the calendar. 

- The date format isn't usable with screen reader Jaws and NVDA. You can put this format directly in a <label > "Date etc"or keep the placeholder (not the better solution because the placeholder disapears when you write something on the field) and put the attributes aria-label (for screen readers) and a "title" attribute to generate a tooltip which will be usefull for people who have concentration problems and cognitive disability for exeample.

**Comment by liyokuna** [comment]
Important points:

## Problem with contrast
- Inside header, change blue on grey to black on grey.
- Today button, change white on orange to white on black.

## Prev and Next Arrow
- Translation in French for demo page

## Placeholder
- Change the place holder from DD/MM/YYYY to in French "Saisir une date ( format jj/mm/aaa)". An example [right here](http://a11y-guidelines.orange.com/web/exemples/formulaire/index.html).
