### ISSUE TITLE
Include Specific Bootstrap Module Instead Of Importing Complete Package

### ISSUE THREAD

**Issue by aakashgarg19** [Orange-OpenSource/Orange-Boosted-Angular#9]
Currently the library is importing complete ngb module like :- 
import {NgbModule} from '@ng-bootstrap/ng-bootstrap'.

It should import specific modules it is using. For eg:- 
import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap/modal/modal.module';

It is required to support tree shaking in final output of the application. Currently it bring whole ng-bootstrap in final output. By importing specific modules we can reduce the size of final output of applications. Please find screenshot of current output for your reference.

![image](https://user-images.githubusercontent.com/13452345/44968732-31fda980-af67-11e8-85e7-2c4907500fb6.png)

**Comment by aakashgarg19** [comment]
Hi @liyokuna, is there any plan for the fix related to this issue?

**Comment by pkozlowski-opensource** [comment]
> Currently the library is importing complete ngb module like :-
import {NgbModule} from '@ng-bootstrap/ng-bootstrap'.
It should import specific modules it is using. For eg:-
import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap/modal/modal.module';

Please note that starting from ng-bootstrap 3.0.0 we are using Angular Package format and as a consequence:
* `import {NgbModule} from '@ng-bootstrap/ng-bootstrap'.` is the _only_ valid and available import;
* `import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap/modal/modal.module';` is invalid and won't work.

Importing from `'@ng-bootstrap/ng-bootstrap'` should be fine and CLI (build optimiser) should tree-shake unused portions of ng-bootstrap. This should work with the latest ng-bootstrap / Angular / CLI.

IMO this issue is invalid and should be closed.

**Comment by aakashgarg19** [comment]
Ok, so can we use ng-bootstrap 3.0.0 with ng-boosted 2.0.0

**Comment by aakashgarg19** [comment]
Hey @pkozlowski-opensource , thanks for the information. I updated the @ng-bootstrap/ng-bootstrap version to 3.2.2 and it seems to work fine now. No unnecessary imports. Thanks a lot.

**Comment by aakashgarg19** [comment]
> > Currently the library is importing complete ngb module like :-
> > import {NgbModule} from '@ng-bootstrap/ng-bootstrap'.
> > It should import specific modules it is using. For eg:-
> > import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
> 
> Please note that starting from ng-bootstrap 3.0.0 we are using Angular Package format and as a consequence:
> 
> * `import {NgbModule} from '@ng-bootstrap/ng-bootstrap'.` is the _only_ valid and available import;
> * `import { NgbModalModule } from '@ng-bootstrap/ng-bootstrap/modal/modal.module';` is invalid and won't work.
> 
> Importing from `'@ng-bootstrap/ng-bootstrap'` should be fine and CLI (build optimiser) should tree-shake unused portions of ng-bootstrap. This should work with the latest ng-bootstrap / Angular / CLI.
> 
> IMO this issue is invalid and should be closed.

Hey @pkozlowski-opensource , thanks for the information. I updated the @ng-bootstrap/ng-bootstrap version to 3.2.2 and it seems to work fine now. No unnecessary imports. Thanks a lot.

**Comment by liyokuna** [comment]
hello @aakashgarg19 !
sorry.
Thanks @pkozlowski-opensource for answer.
